title: Bologna Big Code Lab
email: stefanopio.zingaro@unibo.it
description: >- # this means to ignore newlines until "baseurl:"
  The first public event realized within the Big Code Lab project in Bologna on March 16th. A day dedicated to codes, Open Source and digital archives. 
baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com

# Custom site variables
keywords: Bologna Big Code Lab, Big Code Lab, BoBCL, BCL
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
google-analytics: UA-112361799-6

# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: false

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: true

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
